/**
 * Germany VAT (Umsatzsteuer) Compliance Engine Module
 * Automatically generated by DAI - Flash Autonomous Agent
 */

export interface VatItem {
    id: string;
    description: string;
    netAmount: number;
    vatRate: number; // 19 standard, 7 reduced
}

export interface VatInvoice {
    invoiceNumber: string;
    invoiceDate: string;
    supplierVatId: string;
    recipientVatId?: string;
    recipientCountryCode: string; // ISO 3166-1 alpha-2
    isIntraCommunitySupply: boolean; // B2B reverse charge within EU
    items: VatItem[];
}

export interface VatComputationResult {
    netTotal: number;
    vatTotal: number;
    grandTotal: number;
    reverseCharge: boolean;
    category: 'Domestic' | 'Intra-EU B2B (Reverse Charge)' | 'Export (Outside EU)';
}

export class GermanyVatEngine {
    private static readonly EU_COUNTRY_CODES = new Set([
        'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT',
        'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'
    ]);

    public static validateVatId(vatId: string): { isValid: boolean; countryCode?: string; error?: string } {
        if (!vatId || vatId.length < 4) {
            return { isValid: false, error: 'VAT ID too short.' };
        }
        const normalized = vatId.toUpperCase();
        const vatRegex = /^[A-Z]{2}[0-9A-Z]{2,12}$/;
        if (!vatRegex.test(normalized)) {
            return { isValid: false, error: 'Invalid VAT ID format.' };
        }
        return { isValid: true, countryCode: normalized.substring(0, 2) };
    }

    public static computeInvoiceVat(invoice: VatInvoice): VatComputationResult {
        const recipientCountry = invoice.recipientCountryCode.toUpperCase();
        const isEuRecipient = recipientCountry === 'DE' || this.EU_COUNTRY_CODES.has(recipientCountry);
        const reverseCharge = invoice.isIntraCommunitySupply && recipientCountry !== 'DE' && isEuRecipient && !!invoice.recipientVatId;

        let netTotal = 0;
        let vatTotal = 0;
        for (const item of invoice.items) {
            netTotal += item.netAmount;
            if (!reverseCharge && isEuRecipient) {
                vatTotal += (item.netAmount * item.vatRate) / 100;
            }
        }

        let category: 'Domestic' | 'Intra-EU B2B (Reverse Charge)' | 'Export (Outside EU)' = 'Domestic';
        if (reverseCharge) {
            category = 'Intra-EU B2B (Reverse Charge)';
        } else if (!isEuRecipient) {
            category = 'Export (Outside EU)';
        }

        const grandTotal = netTotal + vatTotal;

        return {
            netTotal: Number(netTotal.toFixed(2)),
            vatTotal: Number(vatTotal.toFixed(2)),
            grandTotal: Number(grandTotal.toFixed(2)),
            reverseCharge,
            category
        };
    }
}
