/**
 * Multi-Country Global Tax Router
 * Automatically generated by DAI - Flash Autonomous Agent
 *
 * Dispatches tax computation requests to the correct country-specific engine.
 */

import { IndiaGstEngine, GSTInvoice, GSTComputationResult } from './indiaGstEngine';
import { GermanyVatEngine, VatInvoice, VatComputationResult } from './germanyVatEngine';

export type SupportedCountry = 'IN' | 'DE';

export type TaxComputationResult =
    | { country: 'IN'; result: GSTComputationResult }
    | { country: 'DE'; result: VatComputationResult };

export class GlobalTaxEngine {
    public static supportedCountries(): SupportedCountry[] {
        return ['IN', 'DE'];
    }

    public static computeTax(country: SupportedCountry, invoice: GSTInvoice | VatInvoice): TaxComputationResult {
        switch (country) {
            case 'IN':
                return { country: 'IN', result: IndiaGstEngine.computeInvoiceTaxes(invoice as GSTInvoice) };
            case 'DE':
                return { country: 'DE', result: GermanyVatEngine.computeInvoiceVat(invoice as VatInvoice) };
            default:
                throw new Error(`Unsupported country/tax jurisdiction: ${country}`);
        }
    }
}
