/**
 * Universal India GST Compliance Engine Module
 * Automatically generated by DAI - Flash Autonomous Agent
 */

export interface GSTItem {
    id: string;
    description: string;
    hsnSacCode: string;
    taxableAmount: number;
    gstRate: number; // e.g., 0, 5, 12, 18, 28
    cessRate?: number; // percentage
    cessPerUnit?: number; // specific cess
    quantity?: number;
}

export interface GSTInvoice {
    invoiceNumber: string;
    invoiceDate: string;
    supplierGstin: string;
    supplierStateCode: string;
    recipientGstin?: string;
    recipientStateCode: string;
    placeOfSupply: string; // state code
    isReverseCharge: boolean;
    isExportOrSez: boolean;
    exportType?: 'sez_lut' | 'sez_igst' | 'export_lut' | 'export_igst';
    items: GSTItem[];
}

export interface GSTComputationResult {
    cgstTotal: number;
    sgstTotal: number;
    igstTotal: number;
    cessTotal: number;
    totalTax: number;
    grandTotal: number;
    b2bCategory: 'B2B' | 'B2C Large' | 'B2C Small' | 'Zero-Rated' | 'Export';
    itcEligible: boolean;
}

export class IndiaGstEngine {
    private static readonly STATE_CODES: Record<string, string> = {
        '01': 'Jammu & Kashmir', '02': 'Himachal Pradesh', '03': 'Punjab', '04': 'Chandigarh',
        '05': 'Uttarakhand', '06': 'Haryana', '07': 'Delhi', '08': 'Rajasthan', '09': 'Uttar Pradesh',
        '10': 'Bihar', '11': 'Sikkim', '12': 'Arunachal Pradesh', '13': 'Nagaland', '14': 'Manipur',
        '15': 'Mizoram', '16': 'Tripura', '17': 'Meghalaya', '18': 'Assam', '19': 'West Bengal',
        '20': 'Jharkhand', '21': 'Odisha', '22': 'Chhattisgarh', '23': 'Madhya Pradesh', '24': 'Gujarat',
        '26': 'Dadra & Nagar Haveli and Daman & Diu', '27': 'Maharashtra', '29': 'Karnataka', '30': 'Goa',
        '31': 'Lakshadweep', '32': 'Kerala', '33': 'Tamil Nadu', '34': 'Puducherry', '35': 'Andaman & Nicobar Islands',
        '36': 'Telangana', '37': 'Andhra Pradesh', '38': 'Ladakh'
    };

    public static validateGstin(gstin: string): { isValid: boolean; stateCode?: string; pan?: string; error?: string } {
        if (!gstin || gstin.length !== 15) {
            return { isValid: false, error: 'GSTIN must be exactly 15 characters long.' };
        }
        const gstinRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
        if (!gstinRegex.test(gstin)) {
            return { isValid: false, error: 'Invalid GSTIN format structure.' };
        }
        const stateCode = gstin.substring(0, 2);
        if (!this.STATE_CODES[stateCode]) {
            return { isValid: false, error: 'Invalid State Code in GSTIN.' };
        }
        const pan = gstin.substring(2, 12);
        return { isValid: true, stateCode, pan };
    }

    public static computeInvoiceTaxes(invoice: GSTInvoice): GSTComputationResult {
        let cgstTotal = 0;
        let sgstTotal = 0;
        let igstTotal = 0;
        let cessTotal = 0;
        let taxableSum = 0;

        const isIntraState = invoice.placeOfSupply === invoice.supplierStateCode;

        for (const item of invoice.items) {
            taxableSum += item.taxableAmount;

            if (invoice.isExportOrSez && (invoice.exportType?.includes('lut'))) {
                // Zero-rated under LUT: No tax payable
                continue;
            }

            const rate = item.gstRate || 0;
            const itemTax = (item.taxableAmount * rate) / 100;

            if (isIntraState) {
                cgstTotal += itemTax / 2;
                sgstTotal += itemTax / 2;
            } else {
                igstTotal += itemTax;
            }

            if (item.cessRate) {
                cessTotal += (item.taxableAmount * item.cessRate) / 100;
            }
            if (item.cessPerUnit && item.quantity) {
                cessTotal += item.cessPerUnit * item.quantity;
            }
        }

        const totalTax = cgstTotal + sgstTotal + igstTotal + cessTotal;
        const grandTotal = taxableSum + totalTax;

        let b2bCategory: 'B2B' | 'B2C Large' | 'B2C Small' | 'Zero-Rated' | 'Export' = 'B2C Small';
        if (invoice.isExportOrSez) {
            b2bCategory = invoice.exportType?.includes('export') ? 'Export' : 'Zero-Rated';
        } else if (invoice.recipientGstin) {
            b2bCategory = 'B2B';
        } else if (!isIntraState && taxableSum > 250000) {
            b2bCategory = 'B2C Large';
        }

        const itcEligible = !invoice.isReverseCharge && b2bCategory === 'B2B';

        return {
            cgstTotal: Number(cgstTotal.toFixed(2)),
            sgstTotal: Number(sgstTotal.toFixed(2)),
            igstTotal: Number(igstTotal.toFixed(2)),
            cessTotal: Number(cessTotal.toFixed(2)),
            totalTax: Number(totalTax.toFixed(2)),
            grandTotal: Number(grandTotal.toFixed(2)),
            b2bCategory,
            itcEligible
        };
    }
}
